version: '3.8'

services:
  product-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WORKSPACE_PATH=apps/product-service # Passa a pata correta aqui
    environment:
      - PORT=3001

  order-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WORKSPACE_PATH=apps/order-service   # Passa a pasta correta aqui
    environment:
      - PORT=3001
      - PRODUCT_SERVICE_URL=http://product-service:3001
    depends_on:
      - product-service

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WORKSPACE_PATH=apps/api-gateway    # Passa a porta aqui
    ports:
      - "3000:3001" # Única porta exposta
    environment:
      - PORT=3001
      - PRODUCT_SERVICE=http://product-service:3001
      - ORDER_SERVICE=http://order-service:3001
    depends_on:
      - product-service
      - order-service