services:
  product-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WORKSPACE_PATH=apps/product-service
    environment:
      - PORT=3001 

  order-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WORKSPACE_PATH=apps/order-service
    environment:
      - PORT=3002 
    depends_on:
      - product-service

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WORKSPACE_PATH=apps/api-gateway
    ports:
      - "3000:3001" 
    environment:
      - PORT=3001
      - PRODUCT_SERVICE=http://product-service:3001
      - ORDER_SERVICE=http://order-service:3002 
    depends_on:
      - product-service
      - order-service